### ISSUE TITLE
Issue with pre-processing dataset (matlab script)

### ISSUE THREAD

**Issue by shakeebmurtaza** [qc17-THU/DL-SR#10]
I tried to process all planes/folders in your BioSR dataset using Matlab code. But Matlab is only processing one folder **(folder)** successfully. It generates errors for other folders. For example, it produces the below-given error for the following folder: "F-actin_Nonlinear". Could you please rectify this issue and provide the code that you used for other planes.

Thank you very much.

![image](https://user-images.githubusercontent.com/11075677/163695337-1fe60945-4f9e-465c-91ab-2b8e48287a88.png)

**Comment by qc17-THU** [comment]
Hi, I have checked your problem and found out this error was induced by the different file names of GT-SIM data, i.e., SIM_gt.mrc (F-actin) v.s. SIM_gt_a.mrc (F-actin_nonlinear). I have committed a change on our MATLAB code, where the variable "GtFilter" was redefined as "SIM_gt*.mrc". Now the matlab code is able to process all folders except ER. ER data was arraged with a different file structure (because of its high dynamics and corresponding imaging configurations), and you could just simply modified the data reading part of the matlab code to process ER data if needed. Hope you enjoy the code :)

**Comment by shakeebmurtaza** [comment]
I encountered another error while processing (F-actin_Nonlinear). Could you please rectify also this issue?


![image](https://user-images.githubusercontent.com/11075677/163786085-60b6e9f3-4d0c-4a0a-960f-2c6bd99af4ef.png)

**Comment by shakeebmurtaza** [comment]
Could you (@qc17-THU) please provide mapping for ER folder. In ER folder I think each level has it's own ground truth right? If yes then which GT folder we have to use. If no then which SIM_gt we are supposed to use. Also which directory I have to include in this path XxDir(CellList{i}, GtFilter).

Thanks in advance.

![image](https://user-images.githubusercontent.com/11075677/163873826-c74bfe25-bd51-4882-b26e-ae9708e358fe.png)

**Comment by qc17-THU** [comment]
Sorry for the late reply. I'm struggling with my doctoral dissertation recently and it nearly kills me :(
You are right that we acquired raw GT SIM images for ER at each signal level because ER cannot be fixed chemically while maintaining its fine structures. The folder "GTSIM" and "RawGTSIMData" contains GT-SIM images (after SIM reconstruction) and raw GT SIM images (before SIM reconstruction) of high SNR, respectively. If you are aimed to train a DLSR model, that is , inferring a SR image directly from its low-res. counterpart, you can used the GT-SIM images in folder "GTSIM" as supervision. And if you want to train a denoising model, the raw GT SIM data will helps.
