### ISSUE TITLE
Discriminator contribution to DFGAN

### ISSUE THREAD

**Issue by IvanHCenalmor** [qc17-THU/DL-SR#14]
Hi,

I have been testing the DFGAN model with a different data set. In order to obtain a better performance I have been trying different parameter configurations and I have realized that the discriminator loss and its predictions do not change to much. In general,  I have distinguished two different performances:
- The discriminator catches the generator (predicting as fake, the generated images) and then the performance of the generator gets worse, generating black or white images.
- The most common performance, the discriminator starts differentiating well between true and fake, but around the batch iteration 400 (quite early) the discriminator starts to predict 0.5 to all the images, not contributing to the training.

Then I tested the original train_DFGAN.py scrip that you have with the original data set of F-actin and it seems to perform like in the second case where, the discriminator returns a 0.5 to all the images.

So, the question is: Does the discriminator really contribute to the training of the model or the improvement of the performance is due to the MSE and SSIM in the loss of the generator? What has happened in your experiments?

Thanks.

**Comment by qc17-THU** [comment]
Hi, the discriminator (D) definitely contributes to the training process of the generator (G). Actually, the second circumstance you described above is the correct case while training a GAN based model, because the purpose of the overall training task (including both G and D) is to let G and D fight each other and evolve together. 
A simple way to validate its effectiveness is that you can train a DFCAN model and a DFGAN model individually with the same SR dataset and apply them to a testing image. The difference of their outputs should be quite evident.
